GCC = gcc
MODULO = modulo
PROGRAMAS = labRendiSantamaria_O
RM = rm -f

labRendiSantamaria_O: $(PROGRAMAS).c $(MODULO).c modulo.h
        $(GCC) $(MODULO).c -c
        $(GCC) $@.c $(MODULO).o -o $@

clear:
        $(RM) $(PROGRAMAS) $(MODULO).o

